In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/agriastra_ai_dataset.csv')

df.head()

       NDVI      NDWI         VH         VV   Rainfall Moisture_Stress
0  0.348767 -0.476177 -20.025476 -12.354627  18.531933        Moderate
1  0.641812 -0.498966 -17.326365  -9.763876  18.531933        Moderate
2  0.826490 -0.700789 -18.558639 -11.072210  18.531933            High
3  0.778754 -0.679737 -19.862415 -10.367734  18.531933            High
4  0.401090 -0.466092 -19.174761 -12.459310  18.531933        Moderate

In [3]:
df.columns

Index(['NDVI', 'NDWI', 'VH', 'VV', 'Rainfall', 'Moisture_Stress'], dtype='object')

In [4]:
def irrigation_advice(stress):

    if stress == 'Low':
        return 'No irrigation needed'

    elif stress == 'Moderate':
        return 'Irrigate within 3 days'

    else:
        return 'Irrigate immediately'

In [5]:
df['Irrigation_Advisory'] = df['Moisture_Stress'].apply(

    irrigation_advice

)

df.head()

,NDVI,NDWI,VH,VV,Rainfall,Moisture_Stress,Irrigation_Advisory
0,0.348767,-0.476177,-20.025476,-12.354627,18.531933,Moderate,Irrigate within 3 days
1,0.641812,-0.498966,-17.326365,-9.763876,18.531933,Moderate,Irrigate within 3 days
2,0.826490,-0.700789,-18.558639,-11.072210,18.531933,High,Irrigate immediately
3,0.778754,-0.679737,-19.862415,-10.367734,18.531933,High,Irrigate immediately
4,0.401090,-0.466092,-19.174761,-12.459310,18.531933,Moderate,Irrigate within 3 days

In [6]:
df['Irrigation_Advisory'].value_counts()

Irrigation_Advisory
Irrigate within 3 days    257
Irrigate immediately      196
No irrigation needed       47
Name: count, dtype: int64

In [7]:
df.to_csv(

    'agriastra_final_dataset.csv',

    index=False

)

print("Final dataset created.")

Final dataset created.